# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

matrix:
  include:
    - os: linux
      r: release
      after_success:
        - Rscript -e 'pkgdown::build_site(examples = FALSE)'
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_PAT
        keep-history: true
        local-dir: docs
        on:
          branch: main

    - os: linux
      r: devel

    - os: osx
      r: release

    - os: osx
      r: devel
