dos2unix -o man/*.*
dos2unix -o R/*.*
dos2unix -o data-raw/*.*
dos2unix -o vignettes/*.*
dos2unix -o tests/*.*
dos2unix -o tests/testthat/*.*
dos2unix -o DESCRIPTION
dos2unix -o NAMESPACE
dos2unix -o *.Rproj
