dos2unix -o figures/*.eps
dos2unix -o figures/*.R
dos2unix -o inst/*.*
dos2unix -o inst/extdata/*.*
dos2unix -o inst/shiny/*.*
dos2unix -o man/*.*
dos2unix -o man-roxygen/*.*
dos2unix -o R/*.*
dos2unix -o src/*.cpp
dos2unix -o tests/*.*
dos2unix -o tests/testthat/*.*
dos2unix -o vignettes/*.*
dos2unix -o .gitignore
dos2unix -o .Rbuildignore
dos2unix -o .travis.yml
dos2unix -o *.md
dos2unix -o DESCRIPTION
dos2unix -o NAMESPACE
dos2unix -o *.Rproj
