#' @references{
#'   \insertRef{lord_theory_1952}{TestDesign}
#' }
#' @references{
#'   \insertRef{birnbaum_efficient_1957}{TestDesign}
#' }
#' @references{
#'   \insertRef{birnbaum_estimation_1958}{TestDesign}
#' }
#' @references{
#'   \insertRef{birnbaum_further_1958}{TestDesign}
#' }
