use_data_raw()

attrib_pool_A = read.csv("data-raw\\attrib_pool_A.csv")
attrib_pool_B = read.csv("data-raw\\attrib_pool_B.csv")
attrib_pool_C = read.csv("data-raw\\attrib_pool_C.csv")
constraints_0 = read.csv("data-raw\\constraints_0.csv")
constraints_1 = read.csv("data-raw\\constraints_1.csv")
par_Pool_A    = read.csv("data-raw\\par_Pool_A.csv", header = F)
par_Pool_B    = read.csv("data-raw\\par_Pool_B.csv", header = F)
par_Pool_C    = read.csv("data-raw\\par_Pool_C.csv", header = F)
par_mixed     = read.csv("data-raw\\par_mixed.csv", header = F)
se_Pool_A     = read.csv("data-raw\\se_Pool_A.csv", header = F)
se_Pool_B     = read.csv("data-raw\\se_Pool_B.csv", header = F)
se_Pool_C     = read.csv("data-raw\\se_Pool_C.csv", header = F)

usethis::use_data(attrib_pool_A, overwrite = T)
usethis::use_data(attrib_pool_B, overwrite = T)
usethis::use_data(attrib_pool_C, overwrite = T)
usethis::use_data(constraints_0, overwrite = T)
usethis::use_data(constraints_1, overwrite = T)
usethis::use_data(par_Pool_A, overwrite = T)
usethis::use_data(par_Pool_B, overwrite = T)
usethis::use_data(par_Pool_C, overwrite = T)
usethis::use_data(par_mixed, overwrite = T)
usethis::use_data(se_Pool_A, overwrite = T)
usethis::use_data(se_Pool_B, overwrite = T)
usethis::use_data(se_Pool_C, overwrite = T)
