# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname e_item
#' @export
e_1pl <- function(x, b) {
    .Call('_TestDesign_e_1pl', PACKAGE = 'TestDesign', x, b)
}

#' @rdname e_item
#' @export
e_2pl <- function(x, a, b) {
    .Call('_TestDesign_e_2pl', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname e_item
#' @export
e_m_2pl <- function(x, a, d) {
    .Call('_TestDesign_e_m_2pl', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname e_item
#' @export
e_3pl <- function(x, a, b, c) {
    .Call('_TestDesign_e_3pl', PACKAGE = 'TestDesign', x, a, b, c)
}

#' @rdname e_item
#' @export
e_m_3pl <- function(x, a, d, c) {
    .Call('_TestDesign_e_m_3pl', PACKAGE = 'TestDesign', x, a, d, c)
}

#' @rdname e_item
#' @export
e_pc <- function(x, b) {
    .Call('_TestDesign_e_pc', PACKAGE = 'TestDesign', x, b)
}

#' @rdname e_item
#' @export
e_gpc <- function(x, a, b) {
    .Call('_TestDesign_e_gpc', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname e_item
#' @export
e_m_gpc <- function(x, a, d) {
    .Call('_TestDesign_e_m_gpc', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname e_item
#' @export
e_gr <- function(x, a, b) {
    .Call('_TestDesign_e_gr', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname e_item
#' @export
e_m_gr <- function(x, a, d) {
    .Call('_TestDesign_e_m_gr', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname e_item
#' @export
array_e_1pl <- function(x, b) {
    .Call('_TestDesign_array_e_1pl', PACKAGE = 'TestDesign', x, b)
}

#' @rdname e_item
#' @export
array_e_2pl <- function(x, a, b) {
    .Call('_TestDesign_array_e_2pl', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname e_item
#' @export
array_e_3pl <- function(x, a, b, c) {
    .Call('_TestDesign_array_e_3pl', PACKAGE = 'TestDesign', x, a, b, c)
}

#' @rdname e_item
#' @export
array_e_pc <- function(x, b) {
    .Call('_TestDesign_array_e_pc', PACKAGE = 'TestDesign', x, b)
}

#' @rdname e_item
#' @export
array_e_gpc <- function(x, a, b) {
    .Call('_TestDesign_array_e_gpc', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname e_item
#' @export
array_e_gr <- function(x, a, b) {
    .Call('_TestDesign_array_e_gr', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname h_item
#' @export
h_1pl <- function(x, b, u) {
    .Call('_TestDesign_h_1pl', PACKAGE = 'TestDesign', x, b, u)
}

#' @rdname h_item
#' @export
h_2pl <- function(x, a, b, u) {
    .Call('_TestDesign_h_2pl', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname h_item
#' @export
h_3pl <- function(x, a, b, c, u) {
    .Call('_TestDesign_h_3pl', PACKAGE = 'TestDesign', x, a, b, c, u)
}

#' @rdname h_item
#' @export
h_pc <- function(x, b, u) {
    .Call('_TestDesign_h_pc', PACKAGE = 'TestDesign', x, b, u)
}

#' @rdname h_item
#' @export
h_gpc <- function(x, a, b, u) {
    .Call('_TestDesign_h_gpc', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname h_item
#' @export
h_gr <- function(x, a, b, u) {
    .Call('_TestDesign_h_gr', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname h_item
#' @export
array_h_1pl <- function(x, b, u) {
    .Call('_TestDesign_array_h_1pl', PACKAGE = 'TestDesign', x, b, u)
}

#' @rdname h_item
#' @export
array_h_2pl <- function(x, a, b, u) {
    .Call('_TestDesign_array_h_2pl', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname h_item
#' @export
array_h_3pl <- function(x, a, b, c, u) {
    .Call('_TestDesign_array_h_3pl', PACKAGE = 'TestDesign', x, a, b, c, u)
}

#' @rdname h_item
#' @export
array_h_pc <- function(x, b, u) {
    .Call('_TestDesign_array_h_pc', PACKAGE = 'TestDesign', x, b, u)
}

#' @rdname h_item
#' @export
array_h_gpc <- function(x, a, b, u) {
    .Call('_TestDesign_array_h_gpc', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname h_item
#' @export
array_h_gr <- function(x, a, b, u) {
    .Call('_TestDesign_array_h_gr', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname calc_info
#' @export
calc_info <- function(x, item_parm, ncat, model) {
    .Call('_TestDesign_calc_info', PACKAGE = 'TestDesign', x, item_parm, ncat, model)
}

#' @rdname calc_info
#' @export
calc_info_matrix <- function(x, item_parm, ncat, model) {
    .Call('_TestDesign_calc_info_matrix', PACKAGE = 'TestDesign', x, item_parm, ncat, model)
}

#' Calculate the Fisher information using empirical Bayes
#'
#' Calculate the Fisher information using empirical Bayes.
#'
#' @param x A numeric vector of MCMC sampled theta values.
#' @param item_parm A numeric matrix of item parameters.
#' @template calc-params-mini
calc_info_EB <- function(x, item_parm, ncat, model) {
    .Call('_TestDesign_calc_info_EB', PACKAGE = 'TestDesign', x, item_parm, ncat, model)
}

#' Calculate the Fisher information using full Bayesian
#'
#' Calculate the Fisher information using full Bayesian.
#'
#' @param x A numeric vector of MCMC sampled theta values.
#' @param items_list A list of item parameter matrices.
#' @template calc-params-mini
#' @param useEAP \code{TRUE} to use the mean of MCMC theta draws.
calc_info_FB <- function(x, items_list, ncat, model, useEAP = FALSE) {
    .Call('_TestDesign_calc_info_FB', PACKAGE = 'TestDesign', x, items_list, ncat, model, useEAP)
}

#' Calculate the mutual information using full Bayesian
#'
#' Calculate the mutual information using full Bayesian.
#'
#' @param x A numeric vector of MCMC sampled theta values.
#' @param items_list A list of item parameter matrices.
#' @template calc-params-mini
calc_MI_FB <- function(x, items_list, ncat, model) {
    .Call('_TestDesign_calc_MI_FB', PACKAGE = 'TestDesign', x, items_list, ncat, model)
}

#' @rdname a_to_alpha
#' @export
a_to_alpha <- function(a) {
    .Call('_TestDesign_a_to_alpha', PACKAGE = 'TestDesign', a)
}

#' @rdname info_item
#' @export
info_1pl <- function(x, b) {
    .Call('_TestDesign_info_1pl', PACKAGE = 'TestDesign', x, b)
}

#' @rdname info_item
#' @export
info_2pl <- function(x, a, b) {
    .Call('_TestDesign_info_2pl', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname info_item
#' @export
info_m_2pl <- function(x, a, d) {
    .Call('_TestDesign_info_m_2pl', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
dirinfo_m_2pl <- function(x, a, d) {
    .Call('_TestDesign_dirinfo_m_2pl', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
thisdirinfo_m_2pl <- function(x, alpha_vec, a, d) {
    .Call('_TestDesign_thisdirinfo_m_2pl', PACKAGE = 'TestDesign', x, alpha_vec, a, d)
}

#' @rdname info_item
#' @export
info_3pl <- function(x, a, b, c) {
    .Call('_TestDesign_info_3pl', PACKAGE = 'TestDesign', x, a, b, c)
}

#' @rdname info_item
#' @export
info_m_3pl <- function(x, a, d, c) {
    .Call('_TestDesign_info_m_3pl', PACKAGE = 'TestDesign', x, a, d, c)
}

#' @rdname info_item
#' @export
dirinfo_m_3pl <- function(x, a, d, c) {
    .Call('_TestDesign_dirinfo_m_3pl', PACKAGE = 'TestDesign', x, a, d, c)
}

#' @rdname info_item
#' @export
thisdirinfo_m_3pl <- function(x, alpha_vec, a, d, c) {
    .Call('_TestDesign_thisdirinfo_m_3pl', PACKAGE = 'TestDesign', x, alpha_vec, a, d, c)
}

#' @rdname info_item
#' @export
info_pc <- function(x, b) {
    .Call('_TestDesign_info_pc', PACKAGE = 'TestDesign', x, b)
}

#' @rdname info_item
#' @export
info_gpc <- function(x, a, b) {
    .Call('_TestDesign_info_gpc', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname info_item
#' @export
info_m_gpc <- function(x, a, d) {
    .Call('_TestDesign_info_m_gpc', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
dirinfo_m_gpc <- function(x, a, d) {
    .Call('_TestDesign_dirinfo_m_gpc', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
thisdirinfo_m_gpc <- function(x, alpha_vec, a, d) {
    .Call('_TestDesign_thisdirinfo_m_gpc', PACKAGE = 'TestDesign', x, alpha_vec, a, d)
}

#' @rdname info_item
#' @export
info_gr <- function(x, a, b) {
    .Call('_TestDesign_info_gr', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname info_item
#' @export
info_m_gr <- function(x, a, d) {
    .Call('_TestDesign_info_m_gr', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
dirinfo_m_gr <- function(x, a, d) {
    .Call('_TestDesign_dirinfo_m_gr', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
thisdirinfo_m_gr <- function(x, alpha_vec, a, d) {
    .Call('_TestDesign_thisdirinfo_m_gr', PACKAGE = 'TestDesign', x, alpha_vec, a, d)
}

#' @rdname info_item
#' @export
array_info_1pl <- function(x, b) {
    .Call('_TestDesign_array_info_1pl', PACKAGE = 'TestDesign', x, b)
}

#' @rdname info_item
#' @export
array_info_2pl <- function(x, a, b) {
    .Call('_TestDesign_array_info_2pl', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname info_item
#' @export
array_info_m_2pl <- function(x, a, d) {
    .Call('_TestDesign_array_info_m_2pl', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
array_dirinfo_m_2pl <- function(x, a, d) {
    .Call('_TestDesign_array_dirinfo_m_2pl', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
array_thisdirinfo_m_2pl <- function(x, alpha_vec, a, d) {
    .Call('_TestDesign_array_thisdirinfo_m_2pl', PACKAGE = 'TestDesign', x, alpha_vec, a, d)
}

#' @rdname info_item
#' @export
array_info_3pl <- function(x, a, b, c) {
    .Call('_TestDesign_array_info_3pl', PACKAGE = 'TestDesign', x, a, b, c)
}

#' @rdname info_item
#' @export
array_info_m_3pl <- function(x, a, d, c) {
    .Call('_TestDesign_array_info_m_3pl', PACKAGE = 'TestDesign', x, a, d, c)
}

#' @rdname info_item
#' @export
array_dirinfo_m_3pl <- function(x, a, d, c) {
    .Call('_TestDesign_array_dirinfo_m_3pl', PACKAGE = 'TestDesign', x, a, d, c)
}

#' @rdname info_item
#' @export
array_thisdirinfo_m_3pl <- function(x, alpha_vec, a, d, c) {
    .Call('_TestDesign_array_thisdirinfo_m_3pl', PACKAGE = 'TestDesign', x, alpha_vec, a, d, c)
}

#' @rdname info_item
#' @export
array_info_pc <- function(x, b) {
    .Call('_TestDesign_array_info_pc', PACKAGE = 'TestDesign', x, b)
}

#' @rdname info_item
#' @export
array_info_gpc <- function(x, a, b) {
    .Call('_TestDesign_array_info_gpc', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname info_item
#' @export
array_info_m_gpc <- function(x, a, d) {
    .Call('_TestDesign_array_info_m_gpc', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
array_dirinfo_m_gpc <- function(x, a, d) {
    .Call('_TestDesign_array_dirinfo_m_gpc', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
array_thisdirinfo_m_gpc <- function(x, alpha_vec, a, d) {
    .Call('_TestDesign_array_thisdirinfo_m_gpc', PACKAGE = 'TestDesign', x, alpha_vec, a, d)
}

#' @rdname info_item
#' @export
array_info_gr <- function(x, a, b) {
    .Call('_TestDesign_array_info_gr', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname info_item
#' @export
array_info_m_gr <- function(x, a, d) {
    .Call('_TestDesign_array_info_m_gr', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
array_dirinfo_m_gr <- function(x, a, d) {
    .Call('_TestDesign_array_dirinfo_m_gr', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname info_item
#' @export
array_thisdirinfo_m_gr <- function(x, alpha_vec, a, d) {
    .Call('_TestDesign_array_thisdirinfo_m_gr', PACKAGE = 'TestDesign', x, alpha_vec, a, d)
}

#' @rdname p_item
#' @export
p_1pl <- function(x, b) {
    .Call('_TestDesign_p_1pl', PACKAGE = 'TestDesign', x, b)
}

#' @rdname p_item
#' @export
p_2pl <- function(x, a, b) {
    .Call('_TestDesign_p_2pl', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname p_item
#' @export
p_m_2pl <- function(x, a, d) {
    .Call('_TestDesign_p_m_2pl', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname p_item
#' @export
p_3pl <- function(x, a, b, c) {
    .Call('_TestDesign_p_3pl', PACKAGE = 'TestDesign', x, a, b, c)
}

#' @rdname p_item
#' @export
p_m_3pl <- function(x, a, d, c) {
    .Call('_TestDesign_p_m_3pl', PACKAGE = 'TestDesign', x, a, d, c)
}

#' @rdname p_item
#' @export
p_pc <- function(x, b) {
    .Call('_TestDesign_p_pc', PACKAGE = 'TestDesign', x, b)
}

#' @rdname p_item
#' @export
p_gpc <- function(x, a, b) {
    .Call('_TestDesign_p_gpc', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname p_item
#' @export
p_m_gpc <- function(x, a, d) {
    .Call('_TestDesign_p_m_gpc', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname p_item
#' @export
p_gr <- function(x, a, b) {
    .Call('_TestDesign_p_gr', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname p_item
#' @export
p_m_gr <- function(x, a, d) {
    .Call('_TestDesign_p_m_gr', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname p_item
#' @export
array_p_1pl <- function(x, b) {
    .Call('_TestDesign_array_p_1pl', PACKAGE = 'TestDesign', x, b)
}

#' @rdname p_item
#' @export
array_p_2pl <- function(x, a, b) {
    .Call('_TestDesign_array_p_2pl', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname p_item
#' @export
array_p_m_2pl <- function(x, a, d) {
    .Call('_TestDesign_array_p_m_2pl', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname p_item
#' @export
array_p_3pl <- function(x, a, b, c) {
    .Call('_TestDesign_array_p_3pl', PACKAGE = 'TestDesign', x, a, b, c)
}

#' @rdname p_item
#' @export
array_p_m_3pl <- function(x, a, d, c) {
    .Call('_TestDesign_array_p_m_3pl', PACKAGE = 'TestDesign', x, a, d, c)
}

#' @rdname p_item
#' @export
array_p_pc <- function(x, b) {
    .Call('_TestDesign_array_p_pc', PACKAGE = 'TestDesign', x, b)
}

#' @rdname p_item
#' @export
array_p_gpc <- function(x, a, b) {
    .Call('_TestDesign_array_p_gpc', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname p_item
#' @export
array_p_m_gpc <- function(x, a, d) {
    .Call('_TestDesign_array_p_m_gpc', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname p_item
#' @export
array_p_gr <- function(x, a, b) {
    .Call('_TestDesign_array_p_gr', PACKAGE = 'TestDesign', x, a, b)
}

#' @rdname p_item
#' @export
array_p_m_gr <- function(x, a, d) {
    .Call('_TestDesign_array_p_m_gr', PACKAGE = 'TestDesign', x, a, d)
}

#' @rdname j_item
#' @export
j_1pl <- function(x, b, u) {
    .Call('_TestDesign_j_1pl', PACKAGE = 'TestDesign', x, b, u)
}

#' @rdname j_item
#' @export
j_2pl <- function(x, a, b, u) {
    .Call('_TestDesign_j_2pl', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname j_item
#' @export
j_m_2pl <- function(x, a, d, u) {
    .Call('_TestDesign_j_m_2pl', PACKAGE = 'TestDesign', x, a, d, u)
}

#' @rdname j_item
#' @export
j_3pl <- function(x, a, b, c, u) {
    .Call('_TestDesign_j_3pl', PACKAGE = 'TestDesign', x, a, b, c, u)
}

#' @rdname j_item
#' @export
j_m_3pl <- function(x, a, d, c, u) {
    .Call('_TestDesign_j_m_3pl', PACKAGE = 'TestDesign', x, a, d, c, u)
}

#' @rdname j_item
#' @export
j_pc <- function(x, b, u) {
    .Call('_TestDesign_j_pc', PACKAGE = 'TestDesign', x, b, u)
}

#' @rdname j_item
#' @export
j_gpc <- function(x, a, b, u) {
    .Call('_TestDesign_j_gpc', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname j_item
#' @export
j_m_gpc <- function(x, a, d, u) {
    .Call('_TestDesign_j_m_gpc', PACKAGE = 'TestDesign', x, a, d, u)
}

#' @rdname j_item
#' @export
j_gr <- function(x, a, b, u) {
    .Call('_TestDesign_j_gr', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname j_item
#' @export
j_m_gr <- function(x, a, d, u) {
    .Call('_TestDesign_j_m_gr', PACKAGE = 'TestDesign', x, a, d, u)
}

#' @rdname j_item
#' @export
array_j_1pl <- function(x, b, u) {
    .Call('_TestDesign_array_j_1pl', PACKAGE = 'TestDesign', x, b, u)
}

#' @rdname j_item
#' @export
array_j_2pl <- function(x, a, b, u) {
    .Call('_TestDesign_array_j_2pl', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname j_item
#' @export
array_j_3pl <- function(x, a, b, c, u) {
    .Call('_TestDesign_array_j_3pl', PACKAGE = 'TestDesign', x, a, b, c, u)
}

#' @rdname j_item
#' @export
array_j_pc <- function(x, b, u) {
    .Call('_TestDesign_array_j_pc', PACKAGE = 'TestDesign', x, b, u)
}

#' @rdname j_item
#' @export
array_j_gpc <- function(x, a, b, u) {
    .Call('_TestDesign_array_j_gpc', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname j_item
#' @export
array_j_gr <- function(x, a, b, u) {
    .Call('_TestDesign_array_j_gr', PACKAGE = 'TestDesign', x, a, b, u)
}

#' @rdname find_segment
#' @export
find_segment <- function(x, segment) {
    .Call('_TestDesign_find_segment', PACKAGE = 'TestDesign', x, segment)
}

#' @noRd
NULL

#' @rdname calc_likelihood
#' @export
calc_likelihood <- function(x, item_parm, resp, ncat, model) {
    .Call('_TestDesign_calc_likelihood', PACKAGE = 'TestDesign', x, item_parm, resp, ncat, model)
}

#' @rdname calc_likelihood
#' @export
calc_likelihood_function <- function(theta_grid, item_parm, resp, ncat, model) {
    .Call('_TestDesign_calc_likelihood_function', PACKAGE = 'TestDesign', theta_grid, item_parm, resp, ncat, model)
}

#' @rdname calc_likelihood
#' @export
calc_log_likelihood <- function(x, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_calc_log_likelihood', PACKAGE = 'TestDesign', x, item_parm, resp, ncat, model, prior, prior_parm)
}

#' @rdname calc_likelihood
#' @export
calc_log_likelihood_function <- function(theta_grid, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_calc_log_likelihood_function', PACKAGE = 'TestDesign', theta_grid, item_parm, resp, ncat, model, prior, prior_parm)
}

#' Calculate a posterior value of theta
#'
#' Calculate a posterior value of theta.
#'
#' @param x A length-one numeric vector for a theta value.
#' @param item_parm A numeric matrix of item parameters.
#' @template calc-params
calc_posterior <- function(x, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_calc_posterior', PACKAGE = 'TestDesign', x, item_parm, resp, ncat, model, prior, prior_parm)
}

#' Calculate a posterior distribution of theta
#'
#' Calculate a posterior distribution of theta.
#'
#' @param theta_grid An equi-spaced grid of theta values.
#' @param item_parm A numeric matrix of item parameters.
#' @template calc-params
calc_posterior_function <- function(theta_grid, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_calc_posterior_function', PACKAGE = 'TestDesign', theta_grid, item_parm, resp, ncat, model, prior, prior_parm)
}

#' Calculate a posterior value of theta for a single item
#'
#' Calculate a posterior value of theta for a single item.
#'
#' @param x A length-one numeric vector for a theta value.
#' @param item_parm A numeric vector of item parameters (for one item).
#' @param resp A length-one numeric vector of item responses.
#' @param ncat A length-one numeric vector of the number of response categories by item.
#' @param model A length-one numeric vector of the IRT model by item (1: 1PL, 2: 2PL, 3: 3PL, 4: PC, 5: GPC, 6: GR).
#' @param prior The type of prior distribution (1: normal, 2: uniform).
#' @param prior_parm A numeric vector of hyperparameters for the prior distribution, c(mu, sigma) or c(ll, ul).
#'
calc_posterior_single <- function(x, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_calc_posterior_single', PACKAGE = 'TestDesign', x, item_parm, resp, ncat, model, prior, prior_parm)
}

#' @rdname theta_EAP
#' @export
theta_EAP <- function(theta_grid, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_theta_EAP', PACKAGE = 'TestDesign', theta_grid, item_parm, resp, ncat, model, prior, prior_parm)
}

#' @rdname theta_EAP
#' @export
theta_EAP_matrix <- function(theta_grid, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_theta_EAP_matrix', PACKAGE = 'TestDesign', theta_grid, item_parm, resp, ncat, model, prior, prior_parm)
}

#' @rdname theta_EB
#' @export
theta_EB <- function(nx, theta_init, theta_prop, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_theta_EB', PACKAGE = 'TestDesign', nx, theta_init, theta_prop, item_parm, resp, ncat, model, prior, prior_parm)
}

#' @rdname theta_EB
#' @export
theta_EB_single <- function(nx, theta_init, theta_prop, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_theta_EB_single', PACKAGE = 'TestDesign', nx, theta_init, theta_prop, item_parm, resp, ncat, model, prior, prior_parm)
}

#' @rdname theta_FB
#' @export
theta_FB <- function(nx, theta_init, theta_prop, items_list, item_init, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_theta_FB', PACKAGE = 'TestDesign', nx, theta_init, theta_prop, items_list, item_init, resp, ncat, model, prior, prior_parm)
}

#' @rdname theta_FB
#' @export
theta_FB_single <- function(nx, theta_init, theta_prop, item_mcmc, item_init, resp, ncat, model, prior, prior_parm) {
    .Call('_TestDesign_theta_FB_single', PACKAGE = 'TestDesign', nx, theta_init, theta_prop, item_mcmc, item_init, resp, ncat, model, prior, prior_parm)
}

