# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calc_info_EB
#'
#' @param x A nice parameter
#' @param item_parm A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
calc_info_EB <- function(x, item_parm, ncat, model) {
    .Call('_Shadow_calc_info_EB', PACKAGE = 'Shadow', x, item_parm, ncat, model)
}

#' calc_info_FB
#'
#' @param x A nice parameter
#' @param items_list A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param useEAP A nice parameter
calc_info_FB <- function(x, items_list, ncat, model, useEAP = FALSE) {
    .Call('_Shadow_calc_info_FB', PACKAGE = 'Shadow', x, items_list, ncat, model, useEAP)
}

#' calc_MI_FB
#'
#' @param x A nice parameter
#' @param items_list A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
calc_MI_FB <- function(x, items_list, ncat, model) {
    .Call('_Shadow_calc_MI_FB', PACKAGE = 'Shadow', x, items_list, ncat, model)
}

#' calc_likelihood
#'
#' @param x A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#'
#' @export
calc_likelihood <- function(x, item_parm, resp, ncat, model) {
    .Call('_Shadow_calc_likelihood', PACKAGE = 'Shadow', x, item_parm, resp, ncat, model)
}

#' calc_likelihood_function
#'
#' @param theta_grid A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#'
#' @export
calc_likelihood_function <- function(theta_grid, item_parm, resp, ncat, model) {
    .Call('_Shadow_calc_likelihood_function', PACKAGE = 'Shadow', theta_grid, item_parm, resp, ncat, model)
}

#' calc_log_likelihood
#'
#' @param x A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
#'
#' @export
calc_log_likelihood <- function(x, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_calc_log_likelihood', PACKAGE = 'Shadow', x, item_parm, resp, ncat, model, prior, prior_parm)
}

#' calc_log_likelihood_function
#'
#' @param theta_grid A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
#'
#' @export
calc_log_likelihood_function <- function(theta_grid, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_calc_log_likelihood_function', PACKAGE = 'Shadow', theta_grid, item_parm, resp, ncat, model, prior, prior_parm)
}

#' calc_posterior
#'
#' @param x A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
#'
#' @export
calc_posterior <- function(x, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_calc_posterior', PACKAGE = 'Shadow', x, item_parm, resp, ncat, model, prior, prior_parm)
}

#' calc_posterior_function
#'
#' @param theta_grid A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
#'
#' @export
calc_posterior_function <- function(theta_grid, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_calc_posterior_function', PACKAGE = 'Shadow', theta_grid, item_parm, resp, ncat, model, prior, prior_parm)
}

#' calc_posterior_single
#'
#' @param x A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
#'
#' @export
calc_posterior_single <- function(x, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_calc_posterior_single', PACKAGE = 'Shadow', x, item_parm, resp, ncat, model, prior, prior_parm)
}

#' theta_EAP
#'
#' @param theta_grid A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
#'
#' @export
theta_EAP <- function(theta_grid, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_theta_EAP', PACKAGE = 'Shadow', theta_grid, item_parm, resp, ncat, model, prior, prior_parm)
}

#' theta_EAP_matrix
#'
#' @param theta_grid A nice parameter
#' @param item_parm A nice parameter
#' @param Resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
#'
#' @export
theta_EAP_matrix <- function(theta_grid, item_parm, Resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_theta_EAP_matrix', PACKAGE = 'Shadow', theta_grid, item_parm, Resp, ncat, model, prior, prior_parm)
}

#' theta_EB
#'
#' @param nx A nice parameter
#' @param theta_init A nice parameter
#' @param theta_prop A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
theta_EB <- function(nx, theta_init, theta_prop, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_theta_EB', PACKAGE = 'Shadow', nx, theta_init, theta_prop, item_parm, resp, ncat, model, prior, prior_parm)
}

#' theta_EB_single
#'
#' @param nx A nice parameter
#' @param theta_init A nice parameter
#' @param theta_prop A nice parameter
#' @param item_parm A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
theta_EB_single <- function(nx, theta_init, theta_prop, item_parm, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_theta_EB_single', PACKAGE = 'Shadow', nx, theta_init, theta_prop, item_parm, resp, ncat, model, prior, prior_parm)
}

#' theta_FB
#'
#' @param nx A nice parameter
#' @param theta_init A nice parameter
#' @param theta_prop A nice parameter
#' @param items_list A nice parameter
#' @param item_init A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
theta_FB <- function(nx, theta_init, theta_prop, items_list, item_init, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_theta_FB', PACKAGE = 'Shadow', nx, theta_init, theta_prop, items_list, item_init, resp, ncat, model, prior, prior_parm)
}

#' theta_FB_single
#'
#' @param nx A nice parameter
#' @param theta_init A nice parameter
#' @param theta_prop A nice parameter
#' @param item_mcmc A nice parameter
#' @param item_init A nice parameter
#' @param resp A nice parameter
#' @param ncat A nice parameter
#' @param model A nice parameter
#' @param prior A nice parameter
#' @param prior_parm A nice parameter
theta_FB_single <- function(nx, theta_init, theta_prop, item_mcmc, item_init, resp, ncat, model, prior, prior_parm) {
    .Call('_Shadow_theta_FB_single', PACKAGE = 'Shadow', nx, theta_init, theta_prop, item_mcmc, item_init, resp, ncat, model, prior, prior_parm)
}

#' findSegment
#'
#' @param segment A nice parameter
#' @param x A nice parameter
#'
#' @export
findSegment <- function(segment, x) {
    .Call('_Shadow_findSegment', PACKAGE = 'Shadow', segment, x)
}

